### ISSUE TITLE
Add support for distinguishing CREATE from UPDATE (and DELETE)

### ISSUE THREAD

**Issue by asgeirn** [FINTprosjektet/fint-event-model#3]
The current model contains a single `action` attribute that combines the operation and target for the event, i.e. `GET_ALL_ARBEIDSFORHOLD`, `GET_ARBEIDSFORHOLD`, `UPDATE_ARBEIDSFORHOLD`.

One improvement (or extension) is to separate these, having a separate attribute for the action (CREATE, READ, UPDATE, DELETE, ...) and the target (ARBEIDSFORHOLD, ELEV, PERSONALRESSURS).

**Comment by jarlehansen** [comment]
I think this is a good improvement, one issue we need to look into if we go for this solution is that the generated Actions class in the model is used for verification that the adapter uses:
https://github.com/FINTprosjektet/fint-sse-adapter-skeleton/blob/master/src/main/java/no/fint/provider/adapter/event/EventStatusService.java

There are probably more places as well that would need to take into account two values instead of the old way where it was just one string.

**Comment by asgeirn** [comment]
Perhaps we should leave the generated Action classes as-is.  In this way the adapter can convey whether it supports only read, or whether it supports any modifications at all.

Then the Operation enum is used to convey the purpose of the modification requested through the consumer.

**Comment by fsjovatsen** [comment]
I think this is a good idea. If we do this we can also deprecate `ACTION` and add a new field called `target`. This will normalize the modell. `ACTION` as it is today has to "informations" - the noun and the subject.

Should we wait a bit before we do this?

**Comment by fsjovatsen** [comment]
What if we do it like this:

1. Add `operation` and `target` as members to the modell and leave them blank for now. Of course we also need to make sure to be backwards compatible.
2. Add values to `operation` and `target`
3. Start implement internal stuff with the new model.
4. Mark `action` as `deprecated`.

Timeline:
1. Before summer we start using the model internally
2. At end of 2019 all adapter vendors is using the new model.


@jarlehansen what do you think?

**Comment by asgeirn** [comment]
Fixed by b091c40e5da4bc80ffc1a48a09414383101f8ff4

**Comment by jarlehansen** [comment]
In the update I can only see Operation added, should it have a target as well? As @fsjovatsen mentioned.

Also, can we start populating these fields already? we should have all the necessary information from action, right?
